### ISSUE TITLE
Danbooru Tag Groups (WHY DOES THIS WEBSITE EXIST) \ Stable Diffusion Tags

### ISSUE THREAD

**Issue by SpaceMageWhatever** [n00mkrad/text2image-gui#102]
it would be nice if the tool had a way to see the tag categories and a way to navigate them
i didnt realize how much the tags matter in the actual generation, and my prompts improved in quality when i turned off the right tags

if you open this page uh, be careful what you click on, i had to gouge my eyes out while browsing this cancer of a website, its pretty disusting
https://danbooru.donmai.us/wiki_pages/tag_groups

i dont know if theres a website for tags which stable diffusion uses, but it would be nice to have, like i had to look up a table of colors which stable diffusion is known to work on and its kinda stupid how spread out everything is right now, the user experience is MEH

ps: apparently "extra fingers" is NOT how you get rid of those weird fingers, you have to type "extra digits"
now excuse me while i go pour eye bleach on my face
https://www.youtube.com/watch?v=OolOpK2Z33g

SOMEBODY SHOOT ME IN THE FACE AAAH-

**Comment by n00mkrad** [comment]
This completely depends on the model training data and does not work for the official SD models, for example. Out of scope.
