### ISSUE TITLE
Prompt being changed to "!reset".

### ISSUE THREAD

**Issue by CyberLykan** [n00mkrad/text2image-gui#14]
Clicking the prompt expand button doesn't work properly. If you click it, it doesn't appear to do anything unless you click it again.
For some reason, this also changes the prompt to "!reset", despite whatever prompt you set yourself.

Noticed on this commit. https://github.com/n00mkrad/text2image-gui/tree/dc2a80175483e6773f357dfd3682548bdf18a12c

**Comment by CyberLykan** [comment]
Additionally, the "!reset" issue seems to also happen when doing more than one run.

**Comment by CyberLykan** [comment]
I think something got messed up with my installation, because the last version I had is facing the same issue.

**Comment by n00mkrad** [comment]
This is WIP stuff meant to work with the updated code which is not yet pushed to the repo.
