### ISSUE TITLE
Is SD running in safe mode?

### ISSUE THREAD

**Issue by andreaaraya01** [n00mkrad/text2image-gui#27]
Hi, I was seaching info about my question but I did not find anything related, so I was trying the tool and I think is excellent, but I have that question, is limited to safe mode or not?.

I hope not break any rule, just asking. thanks in advance.

**Comment by n00mkrad** [comment]
If you mean an NSFW filter, then no, there is no filtering, watermarking, or censorship.

**Comment by andreaaraya01** [comment]
thank so much for your answer, that was that I needed to know.
