### ISSUE TITLE
Where is Dreambooth?

### ISSUE THREAD

**Issue by averkij** [n00mkrad/text2image-gui#29]
Hello! First of all — thank you for the GUI!

I've got the 1.6 version (changelog said that there is dreambooth training), but didn't find the dreambooth functionality. Is it supposed to be in GUI?

![](https://i.imgur.com/7qNIkZL.jpg)

**Comment by n00mkrad** [comment]
Developer Options > Train Dreambooth Model

**Comment by averkij** [comment]
Oh, thanks!
