### ISSUE TITLE
Question: What do you use to package/embed an entire python environment?

### ISSUE THREAD

**Issue by geocine** [n00mkrad/text2image-gui#30]
I have peeked into the code but I am unable to identify how it is being packaged together. I am also new to python so any details will be helpful. Thanks for your work.

**Comment by kft334** [comment]
Having the same issue here I think. Would be great to have the answer to this. Compiling works but the in-app installation doesn't work after compiling. I'm working from version 1.6.0 and copying over a few folders (mb/?) from the official release as a workaround for now. Working with older code isn't optimal, but at least the installation works. Haven't tried it on anything past 1.6.0 but it might work as well.

**Comment by n00mkrad** [comment]
It's just a conda (micromamba to be exact) installation that then installs all packages into a subfolder
