### ISSUE TITLE
Dreambooth on 1.7 change

### ISSUE THREAD

**Issue by xldfy** [n00mkrad/text2image-gui#34]
How come unlike the previous release 512x512 is essentially locked in and forced? Is that Dreambooth's limitation? I've used larger 1:1 images on your 1.6 release and the results were good. 

also

2 quick questions
- what scheduler does it use?
- what is the actual learning rate when the slider is at "1"?

Thank You

**Comment by n00mkrad** [comment]
Pretty sure using >512px images does not have any advantage.

> what scheduler does it use?

Not sure, check here: https://github.com/gammagec/Dreambooth-SD-optimized

> what is the actual learning rate when the slider is at "1"?

dataset size * 0.18 * 0.0000001 * (4000/steps) * 1

**Comment by xldfy** [comment]
huh, looks like they're using DDPM for the scheduler. Anyway, I still think >512px images should result in a warning instead of just not allowing someone to continue. I've head different things in regards to going over that limit. The results I got were still good when I went over so long as the images were 1:1. But it's your GUI do what you want. Thanks for answering my questions.
