### ISSUE TITLE
No CUDA capable GPU detected, but have RTX 2060

### ISSUE THREAD

**Issue by SilentOne1** [n00mkrad/text2image-gui#35]
As stated in title, when I run the NMKD gui, I see in the bot left corner that it says "No CUDA capable GPU detected"
Is it not detecting my RTX 2060? What can I do to fix this?
Thanks

**Comment by n00mkrad** [comment]
Might be caused by a space in your windows username or program installation path.

Try moving the program to a folder without spaces in the path.

**Comment by SilentOne1** [comment]
Got it, thanks.

**Comment by n00mkrad** [comment]
Did it work?

Was the space in your username or elsewhere?

**Comment by SilentOne1** [comment]
The space was in my username, so I'm considering putting it on another user folder to eliminate the problem.
