### ISSUE TITLE
Negative Prompt not Shown or saved into Image Metadata

### ISSUE THREAD

**Issue by mattcaste** [n00mkrad/text2image-gui#36]
I downloaded yesterday the new 1.7.0 version of the GUI.
I tried generating a few images using the Negative Prompt.

It doesn't appear on the left side above the image (the normal prompt appears in green as intended).
It also wasn't saved in the Image metadata (the normal prompt was).

I tried to generate two images with the same prompts and seeds but one with the Negative Prompt and the other without. They came out exactly identical.

My main question for this bug is: is the Negative Prompt used but not shown or it is not used at all?

BTW fantastic work with this GUI! Keep it up!

**Comment by n00mkrad** [comment]
Are you using Low Memory Mode?

Negative prompts don't work there

**Comment by mattcaste** [comment]
Yes I am. 
So that is why they aren't working.

Do they require high VRAM to work?

**Comment by n00mkrad** [comment]
Yes
