### ISSUE TITLE
Python error when opening the application for the second time

### ISSUE THREAD

**Issue by AdamAnon** [n00mkrad/text2image-gui#38]
Starting with version 1.7.0 whenever I launch the application for the second time and click "Generate!" I get this error:

https://www.dropbox.com/s/z4quzd8z604ec23/nmkd-python-error.jpg?raw=1

Until then it was 100% stable. I can only run the application once each time after unzipping. Then I have to delete the entire folder, unzip a fresh copy and start over to be able to run it again. I tried deleting the config.json file, but that doesn't help. Deleting and replacing Data\py folder doesn't help either. I haven't tried the reinstalling feature within the application since unzipping is much faster. Updating to 1.7.1 and updating Nvidia drivers (currently at 526.98) didn't help. Rebooting doesn't help. Windows 11 22H2, RTX3080, 32GB RAM. Thank you!

PS. I wanted to join Discord but they ask for a phone number which is a no no :(

**Comment by n00mkrad** [comment]
You can try 1.7.2 beta which just dropped

https://icedrive.net/s/RwaxNjiyVPTgzTyGVz7NG1zfTGG6

![image](https://user-images.githubusercontent.com/61149547/204341522-a68ce9a4-b37a-4ec5-84b3-8343435b3608.png)

**Comment by n00mkrad** [comment]
Seems like an issue on your end. Are you using Windows 10/11 64-bit with up-to-date graphics drivers?

**Comment by AdamAnon** [comment]
Yeah, Win 11 22H2 x64 with the latest Nvidia drivers, just updated yesterday in response to this issue:( It was running fine, I made no changes to the system. I wonder what causes this then. I had this issue where Windows Desktop Manager was using >90% of my GPU all the time, but your application was running fine despite that and updating Nvidia driver fixed that. Oh well, I'll look around - maybe I'll find what's wrong. Thank you!

**Comment by AdamAnon** [comment]
Looks like I was able to fix it! Some time, ago last week, I've installed Asus RGB control software (Armoury Crate) so I could turn off the annoying lights inside my PC (my RTX3080 runs really hot during image generation and gets loud so I took off the side panel and got blasted with awful RGB lightshow). This is the absolutely most bloated garbage software I have ever had the displeasure of installing on any PC. It takes several times longer to install than Adobe CC and MS Office combined. Absolute bloat! Anyway, it installed 7 or 8 background processes and a bunch of drivers and dlls, including system services. I tried to remove it then, but my PC got a BSOD during uninstallation and the uninstaller failed after reboot, and I had to manually kill all the processes and remove all this garbage from the system. Anyway, after cleaning this up and rebooting my PC, NMKD GUI seems to function properly again!!! I've restarted the application several times today and no errors. In case anyone is interested: avoid Asus software like a plague, you may not be able to remove it! You can download a standalone Open RGB software to disable RGB lights on almost all vendors hardware! No garbage bloat! My PC is nice, dark, fast and stable again. Thank you and apologies for taking your time!

**Comment by n00mkrad** [comment]
Great that it's been resolved
