### ISSUE TITLE
v1.8.0 requires internet connection or model loading will always fail

### ISSUE THREAD

**Issue by fireYtail** [n00mkrad/text2image-gui#44]
I have been using this GUI for quite some time, version 1.7.2 works perfectly without any internet access once everything is installed, if I firewall my whole PC, it still opens, loads the model and works just fine. However, the new version 1.8.0, requires Data\py\python.exe to be able to connect to the internet every single time the model is going to be loaded into memory, and it works fine without internet after that as long as the model isn't unloaded (no disable idle RAM usage etc). If python.exe is firewalled then the GUI will claim that the model file is incompatible. Why did you change this? Is it so that prompts are "secretly" monitored and people can be banned from using Stable Diffusion by IP or something? I find this new take unacceptable... Please provide a way to keep our privacy and stop spying users.

**Comment by San-World** [comment]
Yee, Same here, python.exe want's to use the internet to load a model, even when I block it on firewall on windows, Still communicates, Like it's handshaking, Such a sketchy thing to do, As is it's not portable or offline, , I hope you stop this behaviour in the future. Pleas and Thank You

**Comment by n00mkrad** [comment]
Fixed in 1.8.1

https://github.com/n00mkrad/stable-diffusion-cust/commit/8890a0439678bd245e7e73588c0d4c7fcffea765

**Comment by n00mkrad** [comment]
As a workaround until 1.8.1 is publicly released:

- Open SD GUI, click on Developer Tools (Wrench Button)
- Click on "Open CMD in Python Environment"
- Paste `python -m pip install transformers==4.25.1`
- Close CMD, restart GUI just to be sure

**Comment by fireYtail** [comment]
> Fixed in 1.8.1
> 
> [n00mkrad/stable-diffusion-cust@8890a04](https://github.com/n00mkrad/stable-diffusion-cust/commit/8890a0439678bd245e7e73588c0d4c7fcffea765)

? I download it from here: https://nmkd.itch.io/t2i-gui
Still on 1.8.0

**Comment by n00mkrad** [comment]
> > Fixed in 1.8.1
> > [n00mkrad/stable-diffusion-cust@8890a04](https://github.com/n00mkrad/stable-diffusion-cust/commit/8890a0439678bd245e7e73588c0d4c7fcffea765)
> 
> ? I download it from here: https://nmkd.itch.io/t2i-gui Still on 1.8.0

1.8.1 is not public yet, refer to my previous comment
