### ISSUE TITLE
Can't see model file in other directory

### ISSUE THREAD

**Issue by MarkVorkosigan** [n00mkrad/text2image-gui#48]
I try to use another model (cpkt-file). I added directory with this model (Settings - Stable Diffusion Model - Folders - Add Folder) but NMKD didn't see it. It can only see model when it's placed in NKMD\data\models directory.

**Comment by n00mkrad** [comment]
File size of the model?

**Comment by MarkVorkosigan** [comment]
4 GB. RandoMix3.ckpt.

**Comment by MarkVorkosigan** [comment]
It's because of Comodo Antivirus and its "Auto-Containment mode".

**Comment by n00mkrad** [comment]
> It's because of Comodo Antivirus and its "Auto-Containment mode".

Please uninstall your antivirus.

**All consumer antivirus software is a scam. Windows Defender is all you need, if not more than you need.**
