### ISSUE TITLE
v1.9.0 prompt history copies Windows decimal delimeter causing CFG "5" to be used (also happens on v1.8.*)

### ISSUE THREAD

**Issue by fireYtail** [n00mkrad/text2image-gui#51]
Another bug I found. I run NMKD on my PC, Windows 10 Spanish language and regional settings. Spanish decimal delimiter is commas (,) which is used when copying multiple CFG values from prompt history. The long syntax is always used when copying from history, so the short syntax "10 > 12.5 : 0.5" (= "10, 10.5, 11, 11.5, 12, 12.5") will work correctly, however it is not copied from history, instead forcing the syntax **"10, 10, 5, 11, 11, 5, 12, 12, 5"**, which in turn causes the halves not to work, instead using the not-decimal part first and then the CFG value **"5"** in a second image generation. This means the previous syntax does "10 twice, 5 once, 11 twice, 5 once, 12 twice, 5 once", which is not the expected behaviour. _I guess people on the internet still don't notice Europe exists..._

**Comment by fireYtail** [comment]
One week later I am using the updated v1.8.1 and it still happens and no answer whatsoever because who cares

**Comment by fireYtail** [comment]
Must be very difficult to fix to make it always use a period instead of look it up on Windows regional settings... _Sigh_

**Comment by fireYtail** [comment]
Data\promptHistory.json

"scales": "[10**.**0, 10**.**5,11**.**0,11**.**5,12**.**0,12**.**5]",

The GUI when it uses this file it created:

CFG: 10, 10**,**5,11,11**,**5,12,12**,**5

(The spaces between the commas are ignored but they are read, however the decimal delimiter is read from Windows language, not from the string in the file)

**Comment by n00mkrad** [comment]
Will look into it

**Comment by fireYtail** [comment]
Just updated to 1.9.0 , over a month after opening this issue, you still won't fix it.

**Comment by fireYtail** [comment]
Guess Europeans don't matter.

**Comment by n00mkrad** [comment]
> Guess Europeans don't matter.

Guess where the fck I'm from?
And guess what decimal separators we use?

Yeah that was rhetoric, I'm German and we use comma as decimal separators as well.

I am employed and have a social life, on most days I spend literally all my remaining free time working on my software.
1.9.0 was released ahead of schedule because I wanted to get InstructPix2Pix out there.

But of course your specific bug is more important than my life, huh?

**Comment by n00mkrad** [comment]
I will fix it if I can reproduce it.
In the meantime you could get a massage or a therapy session, whatever helps you to calm down and stop being an ungrateful leech.

**Comment by n00mkrad** [comment]
> Data\promptHistory.json
> 
> "scales": "[10.0,10.5,11.0,11.5,12.0,12.5]",
> 
> The GUI when it reads this file it created:
> 
> CFG: 10, 10,5, 11, 11,5, 12, 12,5
> 
> (The spaces between the commas are inserted but they are irrelevant, it doesn't matter if there are spaces or not, same result)

Also I don't understand the problem, this part is fine, is it not?
The JSON is in English format, so is the UI.
Where's the part where the problem occurs?

**Comment by n00mkrad** [comment]
Done

https://github.com/n00mkrad/text2image-gui/commit/aad8e97c0f8204f75ff3df29ccf2b069666b865f

**Comment by fireYtail** [comment]
> Guess where the fck I'm from?

Very well-mannered. Also, too scared to type the u?

> I am employed

Who asked? And why are you telling your life on a GitHub issue thread? Is your life relevant to the software not working properly? Would your unemployement make it suddenly work? Or maybe you want a medal because you have some money to survive with?

> and have a social life

Nice insinuation, but it's irrelevant whether I do or not, and ad hominem fallacy isn't going to help your narrative anyway.

> ahead of schedule

So there's a schedule now. A schedule in which adding 3 characters to a line of code takes 5 weeks.

> But of course your specific bug is more important than my life, huh?

The bug is not mine, as any European Windows computer can reproduce it. Also, if you think some random internet strangers will care about your life, good luck. You're gonna need it.

> if I can reproduce it

A couple mouse clicks too difficult? Or maybe have problems to press a few keys on the keyboard?

> In the meantime you could get a massage or a therapy session

Thanks your kind suggestion, which again has nothing to do with this software, and is none of your business either, or something you should be mentioning on GitHub.

> ungrateful leech

Thank you. I will try to be more grateful from now on, because you added 3 characters to a line of code 5 weeks later, and only replied with a 4 words message after I kept insisting and being ignored 😉

**Comment by fireYtail** [comment]
Your deleted message:

> Also I don't understand the problem, this part is fine, is it not? The JSON is in English format, so is the UI. Where's the part where the problem occurs?

That as I was saying, upon pressing on that big GENERATE button it would use CFG 5.

**Comment by FelixKainz** [comment]
Jeez fire, you should really look at how you are talking to people.
I myself think I come off like this sometimes but I don't think one should defend it. You do really sound like a demanding dick in this thread. You have no reason to be impolite here. As nmkd said, he is providing his free time to us mostly free of charge, you have absolutely no _right_ to domand anything from him.
Insiting on it and getting more and more impolite won't change that.
