### ISSUE TITLE
How do I download previous versions?

### ISSUE THREAD

**Issue by BibaDev** [n00mkrad/text2image-gui#53]
Good day.

Unfortunately version 1.8.0 does not work, at the end of the generation of the video card error.
There were no such problems with 1.7.2!
On itch I can not download the previous version.

Why don't you publish releases on github?
Where can I download version 1.7.2?

**Comment by raynerbest** [comment]
Hi, I have the same questions @BibaDev . I hope the team can help us soon

**Comment by n00mkrad** [comment]
You can get 1.7.2 here.

https://icedrive.net/s/W7BCV8hG9ZiR2hNBgCAwVRSZvkzQ

Can you tell me more about the issues you're having in 1.8.0?

**Comment by raynerbest** [comment]
Yes, I am not sure if this a normal behavior but, for example when I drag and drop an image created with a previous version of the software into the app, with previous version it loads the image and the metadata but in this version only happens with a few pictures. 
Also I load some models without trouble like the dreamlike model but for some reason stop loading it and a error message show up saying that the model could be incompatible.

**Comment by raynerbest** [comment]
> You can get 1.7.2 here.
> 
> https://icedrive.net/s/W7BCV8hG9ZiR2hNBgCAwVRSZvkzQ
> 
> Can you tell me more about the issues you're having in 1.8.0?

Thanks for the link! 👍😁
