### ISSUE TITLE
Depending on .ckpt model used, the negative prompt box disappears

### ISSUE THREAD

**Issue by mulvainy** [n00mkrad/text2image-gui#63]
Hi, 
Firstly, thanks for your efforts creating this gem!

I have the application working with negative prompt box available for the model provided in the initial download, however when I use sd-v1-5-inpainting.ckpt for the model, the negative prompt box disappears.
Is this expected behaviour when changing models?

**Comment by n00mkrad** [comment]
Negative prompts (and weighting) does not work with the inpainting model for now
