### ISSUE TITLE
Downloaded models not selectable

### ISSUE THREAD

**Issue by Chris-R-R** [n00mkrad/text2image-gui#73]
I downloaded the protogen infinity model from https://civitai.com/models/4398/protogen-infinity-official-release and placed the ckpt file in Data\models but it does not show up in the "Stable Diffusion Model" dropdown even after refreshing the list. Is the model incompatible with NMKD or is there some bug causing it to not appear in the list?

It would be good if there was some info on what models are compatible.

**Comment by n00mkrad** [comment]
Download safetensors version, then convert to Ckpt using Model Converter in SD GUI.

Native Safetensors support is coming in the future.
