### ISSUE TITLE
v1.9.0 InstructPix2Pix requires internet connection to work

### ISSUE THREAD

**Issue by fireYtail** [n00mkrad/text2image-gui#74]
[I guess people never learn from their mistakes...](https://github.com/n00mkrad/text2image-gui/issues/44)

**Comment by n00mkrad** [comment]
This is a `Diffusers` bug, no need to leave a snarky comment here.

**Comment by n00mkrad** [comment]
I already fixed this 2 days ago in https://github.com/n00mkrad/stable-diffusion-cust/commit/0c3a770e2bccf6daf42736a3b261bcd218bfb4d1

Update will be live soon.
