### ISSUE TITLE
Does not load StabilityAI 2.0 or 2.1

### ISSUE THREAD

**Issue by CerebralSeed** [n00mkrad/text2image-gui#88]
In order to duplicate the issue:
1. Install NMKD Stable Diffusion 1.9
2. Download and install any of the StabilityAI models 2.0 or 2.1: https://huggingface.co/stabilityai/stable-diffusion-2-1/tree/main
3. Load the model

Error given: "Failed to load model. The model appears to be incompatible."

Used on Windows 10

Works with other models.

**Comment by n00mkrad** [comment]
1.9 does not support 2.x

1.10 beta (see Discord or wait for release) does
